"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sntyuc+-$x*c3(nw4fyqqh1cuwr6uvw_s-!_z__e7^ge^==_zj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'boards'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Media files (user uploads)

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / "media"

# Uploaded images: accepted formats and maximum file size.
ALLOWED_IMAGE_FORMATS = ("JPEG", "PNG", "GIF", "WEBP")

ALLOWED_IMAGE_EXTENSIONS = ("jpg", "jpeg", "png", "gif", "webp")

MAX_IMAGE_SIZE = 5 * 1024 * 1024

# Bounding box (width, height) for the thumbnail shown in threads and the
# catalogue. Originals within this box are served directly without a thumbnail.
THUMBNAIL_SIZE = (250, 250)

# Reject a post whose text is identical to another post made to the same thread
# (replies) or board (new threads) within this many seconds. Guards against
# double-submits and rapid reposts.
DUPLICATE_POST_WINDOW_SECONDS = 120

# Minimum time a single IP must wait between posts (thread or reply). Basic
# flood protection independent of content.
RATE_LIMIT_REPLY_COOLDOWN_SECONDS = 10

# An IP may start at most RATE_LIMIT_THREAD_MAX threads (across all boards)
# within this many seconds.
RATE_LIMIT_THREAD_WINDOW_SECONDS = 600
RATE_LIMIT_THREAD_MAX = 3

# Set to True only when the app runs behind a reverse proxy that sets a
# trustworthy X-Forwarded-For header; otherwise poster IPs come from REMOTE_ADDR.
TRUST_X_FORWARDED_FOR = False


# Authentication (moderation area)

LOGIN_URL = "mod-login"

LOGIN_REDIRECT_URL = "mod-dashboard"

LOGOUT_REDIRECT_URL = "mod-login"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
