# Generated by Django 6.1 on 2026-08-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_thread_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='boards.post')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='boards.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_post_reference')],
            },
        ),
    ]
