# Generated by Django 6.1 on 2026-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_postreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bump_limit',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
