# Generated by Django 6.1 on 2026-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_bump_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pinned', '-bumped_at']},
        ),
        migrations.AlterField(
            model_name='thread',
            name='bumped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
