# Generated by Django 6.1 on 2026-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_thread_options_alter_thread_bumped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='catalogue_replies',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='board',
            name='threads_per_page',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
