# Generated by Django 6.1 on 2026-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_post_content_alter_thread_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='allows_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='allows_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
