# Generated by Django 6.1 on 2026-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_modaction_kind_ban_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
