# Generated by Django 6.1 on 2026-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_post_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='poster_tripcode',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
