# Generated by Django 6.1 on 2026-09-06 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_post_is_sage_post_poster_tripcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['ip_address', 'lifted_at'], name='boards_ban_ip_addr_4ce3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['poster_ip', 'created_at'], name='boards_post_poster__7d3b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='boards_post_thread__01022c_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['board', 'deleted', 'pinned', 'bumped_at'], name='boards_thre_board_i_7ec25c_idx'),
        ),
    ]
