# Generated by Django 6.1 on 2026-09-06 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_hot_path_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='thread',
            name='boards_thre_board_i_7ec25c_idx',
        ),
        migrations.AddField(
            model_name='board',
            name='max_pages',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='thread',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['board', 'deleted', 'archived', 'pinned', 'bumped_at'], name='boards_thre_board_i_e3f731_idx'),
        ),
    ]
